{
 "title": "APM Anomaly Detection - Pascale Nancy Alia AKPO",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Log Volume per Batch",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "apm_log_count", "legendFormat": "Volume" }
   ]
  },
  {
   "title": "Anomaly Score (ML)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "apm_anomaly_score", "legendFormat": "Score" }
   ]
  },
  {
   "title": "Statut (Dernière détection)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "apm_is_anomaly", "legendFormat": "Statut" }
   ]
  }
 ]
}