# Copyright par Pascale Nancy Alia AKPO
FROM python:3.9-slim

WORKDIR /app

COPY requirements_producer.txt .
RUN pip install --no-cache-dir -r requirements_producer.txt

COPY producer.py .

CMD ["python", "producer.py"]
